common i am remote
let see how to fix the bug here
I need some other log for test
#this is new line here remotely and locally
#this is the new python
# it almost ready to merge to master branch
username = input("What's your name?")

print("Hello there" +username)
